export enum PharmacyEventsEnum{
    DRUG_ORDER_CREATED = 'DRUG_ORDER_CREATED',
    DRUG_ORDER_UPDATED = 'DRUG_ORDER_UPDATED',
    DRUG_ORDER_DELETED = 'DRUG_ORDER_DELETED',
    DRUG_ORDER_DISPENSED = 'DRUG_ORDER_DISPENSED',
    DRUG_ORDER_REJECTED = 'DRUG_ORDER_REJECTED',
}
