export enum WardEventEnum {
    PATIENT_DISCHARGED = "PATIENT_DISCHARGED",
    PATIENT_TRANSFERRED = "PATIENT_TRANSFERRED",
    PATIENT_DISCHARGED_FOR_DEATH = "PATIENT_DISCHARGED_FOR_DEATH",
    PATIENT_ADMITTED = "PATIENT_ADMITTED",
    PATIENT_ADMITTED_FOR_EMERGENCY = "PATIENT_ADMITTED_FOR_EMERGENCY",
    PATIENT_ADMITTED_FOR_SURGERY = "PATIENT_ADMITTED_FOR_SURGERY",
}