/**
 * operation: Isiala-Ngwa North
 * name: Isiala Ngwa North
 * id:wrheiwuyrwehskjdfhkj1212
 *
 */

export enum CameroonLocalGovernmentsEnum {
  'Faro' = 'Faro',
  'Bénoué' = 'Bénoué',
  'Mayo-Louti' = 'Mayo-Louti',
  'Mayo-Rey' = 'Mayo-Rey',
  'Haute-Sanaga' = 'Haute-Sanaga',
  'Lekié' = 'Lekié',
  'Mbam-et-Inoubou' = 'Mbam-et-Inoubou',
  'Mbam-et-Kim' = 'Mbam-et-Kim',
  'Méfou-et-Afamba' = 'Méfou-et-Afamba',
  'Méfou-et-Akono' = 'Méfou-et-Akono',
  'Mfoundi' = 'Mfoundi',
  'Nyong-et-Kéllé' = 'Nyong-et-Kéllé',
  'Nyong-et-Mfoumou' = 'Nyong-et-Mfoumou',
  'Nyong-et-So o' = 'Nyong-et-So o',
  'Moungo' = 'Moungo',
  'Nkam' = 'Nkam',
  'Sanaga-Maritime' = 'Sanaga-Maritime',
  'Wouri' = 'Wouri',
  'Boyo' = 'Boyo',
  'Bui' = 'Bui',
  'Donga-Mantung' = 'Donga-Mantung',
  'Menchum' = 'Menchum',
  'Mezam' = 'Mezam',
  'Momo' = 'Momo',
  'Ngo-ketunjia' = 'Ngo-ketunjia',
  'Diamaré' = 'Diamaré',
  'Logone-et-Chari' = 'Logone-et-Chari',
  'Mayo-Danay' = 'Mayo-Danay',
  'Mayo-Kani' = 'Mayo-Kani',
  'Mayo-Sava' = 'Mayo-Sava',
  'Mayo-Tsanaga' = 'Mayo-Tsanaga',
  'Djérem' = 'Djérem',
  'Faro-et-Déo' = 'Faro-et-Déo',
  'Mayo-Banyo' = 'Mayo-Banyo',
  'Mbéré' = 'Mbéré',
  'Vina' = 'Vina',
  'Boumba-et-Ngoko' = 'Boumba-et-Ngoko',
  'Haut-Nyong' = 'Haut-Nyong',
  'Kadey' = 'Kadey',
  'Lom-et-Djerem' = 'Lom-et-Djerem',
  'Dja-et-Lobo' = 'Dja-et-Lobo',
  'Mvila' = 'Mvila',
  'Océan' = 'Océan',
  'Vallée-du-Ntem' = 'Vallée-du-Ntem',
  'Fako' = 'Fako',
  'Koupé-Manengouba' = 'Koupé-Manengouba',
  'Lebialem' = 'Lebialem',
  'Manyu' = 'Manyu',
  'Meme' = 'Meme',
  'Ndian' = 'Ndian',
  'Bamboutos' = 'Bamboutos',
  'Haut-Nkam' = 'Haut-Nkam',
  'Hauts-Plateaux' = 'Hauts-Plateaux',
  'Koung-Khi' = 'Koung-Khi',
  'Menoua' = 'Menoua',
  'Mifi' = 'Mifi',
  'Ndé' = 'Ndé',
  'Noun' = 'Noun',
}
