"use strict";
exports.__esModule = true;
exports.NigerianStatesEnum = void 0;
var NigerianStatesEnum;
(function (NigerianStatesEnum) {
    NigerianStatesEnum["Abia"] = "Abia";
    NigerianStatesEnum["Adamawa"] = "Adamawa";
    NigerianStatesEnum["AkwaIbom"] = "Akwa Ibom";
    NigerianStatesEnum["Anambra"] = "Anambra";
    NigerianStatesEnum["Bauchi"] = "Bauchi";
    NigerianStatesEnum["Bayelsa"] = "Bayelsa";
    NigerianStatesEnum["Benue"] = "Benue";
    NigerianStatesEnum["Borno"] = "Borno";
    NigerianStatesEnum["CrossRiver"] = "Cross River";
    NigerianStatesEnum["Delta"] = "Delta";
    NigerianStatesEnum["Ebonyi"] = "Ebonyi";
    NigerianStatesEnum["Edo"] = "Edo";
    NigerianStatesEnum["Ekiti"] = "Ekiti";
    NigerianStatesEnum["Enugu"] = "Enugu";
    NigerianStatesEnum["FCT"] = "FCT";
    NigerianStatesEnum["Gombe"] = "Gombe";
    NigerianStatesEnum["Imo"] = "Imo";
    NigerianStatesEnum["Jigawa"] = "Jigawa";
    NigerianStatesEnum["Kaduna"] = "Kaduna";
    NigerianStatesEnum["Kano"] = "Kano";
    NigerianStatesEnum["Katsina"] = "Katsina";
    NigerianStatesEnum["Kebbi"] = "Kebbi";
    NigerianStatesEnum["Kogi"] = "Kogi";
    NigerianStatesEnum["Kwara"] = "Kwara";
    NigerianStatesEnum["Lagos"] = "Lagos";
    NigerianStatesEnum["Nasarawa"] = "Nasarawa";
    NigerianStatesEnum["Niger"] = "Niger";
    NigerianStatesEnum["Ogun"] = "Ogun";
    NigerianStatesEnum["Ondo"] = "Ondo";
    NigerianStatesEnum["Osun"] = "Osun";
    NigerianStatesEnum["Oyo"] = "Oyo";
    NigerianStatesEnum["Plateau"] = "Plateau";
    NigerianStatesEnum["Rivers"] = "Rivers";
    NigerianStatesEnum["Sokoto"] = "Sokoto";
    NigerianStatesEnum["Taraba"] = "Taraba";
    NigerianStatesEnum["Yobe"] = "Yobe";
    NigerianStatesEnum["Zamfara"] = "Zamfara";
})(NigerianStatesEnum = exports.NigerianStatesEnum || (exports.NigerianStatesEnum = {}));
