export enum DesignationEventEnum {
    TRANSACTION_TYPE_CREATED = "TRANSACTION_TYPE_CREATED",
    DESIGNATION_BEFORE_UPDATE = "DESIGNATION_BEFORE_UPDATE",
    DESIGNATION_AFTER_UPDATE = "DESIGNATION_AFTER_UPDATE",
}