export enum PaymentEventEnum {
    PAYMENT_CREATED = "PAYMENT_CREATED",
    PAYMENT_UPDATED = "PAYMENT_UPDATED",
    PAYMENT_DELETED = "PAYMENT_DELETED",
    PAYMENT_CREATED_FROM_MOBILE_ORDER='PAYMENT_CREATED_FROM_MOBILE_ORDER',
    PAYMENT_CREATED_FOR_PHARMACY='PAYMENT_CREATED_FOR_PHARMACY',
    PAYMENT_WITH_CASH_OR_HMO = 'PAYMENT_WITH_CASH_OR_HMO',
}