export const envConfig = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  CONNECTION_STRING: 'CONNECTION_STRING',
  NODEMAILER_USER: 'NODEMAILER_USER',
  NODEMAILER_PASS: 'NODEMAILER_PASS',
  JWT_SECRET: 'JWT_SECRET',
  TOKEN_SECRET: 'TOKEN_SECRET',
  JWT_LIFESPAN: 'JWT_LIFESPAN'
};

