export enum DefaultRolesEnum {
  DEFAULT_DISTRICT_ADMIN_ROLE = 'DEFAULT_DISTRICT_ADMIN_ROLE',
  DEFAULT_STATE_ADMIN_ROLE = 'DEFAULT_STATE_ADMIN_ROLE',
  DEFAULT_DISTRICT_STAFF_ROLE = 'DEFAULT_STAFF_ROLE',
  DEFAULT_SCHOOL_STAFF_ROLE = 'DEFAULT_SCHOOL_STAFF_ROLE',
  DEFAULT_SCHOOL_ADMIN_ROLE = 'DEFAULT_SCHOOL_ADMIN_ROLE',
  DEFAULT_STUDENT_ROLE = 'DEFAULT_STUDENT_ROLE',
  DEFAULT_STATE_STAFF_ROLE = 'DEFAULT_STATE_STAFF_ROLE',
  DEFAULT_CBT_ADMIN = 'DEFAULT_CBT_ADMIN',
  DEFAULT_FUTUREX_ADMIN_ROLE = 'DEFAULT_FUTUREX_ADMIN_ROLE',
  DEFAULT_SUPER_STATE_ADMIN_ROLE = 'DEFAULT_SUPER_STATE_ADMIN_ROLE',
  DEFAULT_SUPER_DISTRICT_ADMIN_ROLE = 'DEFAULT_SUPER_DISTRICT_ADMIN_ROLE',
  DEFAULT_SUPER_SCHOOL_ADMIN_ROLE = 'DEFAULT_SUPER_SCHOOL_ADMIN_ROLE',
}
